version: '3.8'

services:
  # 1. Database MongoDB
  mongodb:
    image: mongo:latest
    container_name: apple_store_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - apple_store_net

  # 2. Giao diện quản lý Database (Thay thế cho MongoDB Compass)
  mongo-express:
    image: mongo-express:latest
    container_name: apple_store_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-1234567890llll@}
    depends_on:
      - mongodb
    networks:
      - apple_store_net

  # 3. Backend APa
  app-server:
    build: ./server
    container_name: apple_store_server
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGODB_URI: mongodb://mongodb:27017/apple-store
      JWT_SECRET: ${JWT_SECRET:-1234567890llll@}
      JWT_EXPIRE: 7d
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4000
    depends_on:
      - mongodb
    networks:
      - apple_store_net

  # 4. Frontend Client
  app-client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:5001/api
    container_name: apple_store_client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app-server
    networks:
      - apple_store_net

  # 5. Frontend Admin
  app-admin:
    build:
      context: ./admin
      args:
        VITE_API_URL: http://localhost:5001/api
    container_name: apple_store_admin
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - app-server
    networks:
      - apple_store_net

networks:
  apple_store_net:
    driver: bridge

volumes:
  mongodb_data:
